frequency: 60
max_height: 0.5
hover_height: 0.3

pitch_kp: 0.5
pitch_ki: 0.0
pitch_kd: 0.0
  
roll_kp: 0.5
roll_ki: 0.0
roll_kd: 0.0
  
yaw_kp: 0.0
yaw_ki: 0.0
yaw_kd: 0.0

throttle_kp: 30.0
throttle_ki: 15.0
throttle_kd: 10.0
